services:
  server:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.21.10
      MEMORY: "10G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD:-supersecret}
      ENABLE_QUERY: "true"
      MOTD: "YEAH!"
      DIFFICULTY: normal
      MODE: survival
      WHITELIST: |
        Aurelion__
        Cchheeff
        DerDreckigeDan
        Djan1k
        Drex_001
        F_L_I_X
        FashleHD
        Floixx
        Goassnflexer
        Hirion42
        Iffu
        InfiniteLevel
        Janiskus_Heslo
        Leoleonhard55
        M0rEZ
        MSAT_Gaming
        MrEnd_MC
        Sev_Fix
        Souper_Fox
        Sushirolle3_0
        Uglubathr
        Wizard_4321
        Xenophonium
        felixf15
        miritzu
        ozonemining
        peschelon
        quietspan
        seibsan
        yungmoxer
        RusskiCraft
        ThatFriendlyGuy
        Pojo64
      OPS: |
        DerDreckigeDan
      VANILLATWEAKS_FILE: /config/vt-datapacks.json,/config/vt-craftingtweaks.json
      MODRINTH_PROJECTS: |
        anti-xray
        areas
        armorstandeditor
        c2me-fabric
        clumps
        conduits-prevent-drowned
        cycle-paintings
        fabric-api
        ferrite-core
        headindex
        inventory-totem
        invview
        lithium
        netherportalfix
        replanting-crops
        scalablelux
        secure-crops
        terralith
        tree-harvester
      NOT_YET_ON_NEWEST_VERSION: |
        krypton
        ore_plus
        distanthorizons:2.3.6-b-1.21.10 # buggy
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      SEED: "-2124094445"
      SPAWN_PROTECTION: 0
      TZ: Europe/Berlin
    volumes:
      # - ./snowy-biomes-mod/build/libs:/mods
      - ./config:/config
      - ./mods:/mods
      - data:/data
    networks:
      - mc-router
    labels:
      mc-router.host: "winter.dummsuff.com,winter.mc.dummsuff.com"

  backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "24h"
      BACKUP_RETENTION_DAYS: "3"
      INITIAL_DELAY: "180s"
      RCON_HOST: server
      TAR_COMPRESS_METHOD: zstd
      RCON_PASSWORD: ${RCON_PASSWORD:-supersecret}
      TZ: "Europe/Berlin"
    volumes:
      - data:/data:ro
      - backups:/backups
    networks:
      - mc-router
    depends_on:
      - server

  copyparty:
    image: copyparty/ac:latest
    user: "1000:1000"
    ports:
      - 3923:3923
    volumes:
      - ./copyparty.conf:/cfg/copyparty.conf:z
      - data:/data:z
      - backups:/backups:z

    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)

      PYTHONUNBUFFERED: 1
      # ensures log-messages are not delayed (but can reduce speed a tiny bit)

    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter 
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s

volumes:
  data:
  backups:

networks:
  mc-router:
    external: true
